name: equality_sample
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: dustin <dcgraham7@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  equatable: ^0.2.5
  built_value: ^6.5.0
  built_collection: ^4.2.2
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  built_value_generator: ^6.5.0
  build_runner: ^1.5.0
